repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  # https://pycqa.github.io/isort/docs/configuration/black_compatibility.html
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black, --filter-files]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  # FIXME: use mypy and debug issues
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.971
  #   hooks:
  #   - id: mypy

  # FIXME: configure with https://pypi.org/project/setup-py-upgrade/
  # - repo: https://github.com/asottile/setup-cfg-fmt
  #   rev: v2.2.0
  #   hooks:
  #   - id: setup-cfg-fmt

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.6.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]
      # https://github.com/macisamuele/language-formatters-pre-commit-hooks/issues/132
      # - id: pretty-format-yaml
      #   args: [--autofix]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
