[project]
name = "SlugTools API"
version = ""
description = "🔧 Simple REST API to return compiled data on university services"
authors = [
    {name = "Harsh Dadhich", email = "hdadhich01@gmail.com"},
]
dependencies = ["beautifulsoup4", "cchardet", "deta", "flask", "flask-compress", "flask-cors", "flask-limiter", "gunicorn", "httpx", "humanize", "lxml", "orjson", "python-dotenv", "round-nutrition", "schedule", "sentry-sdk[flask]", "thefuzz[speedup]"]
requires-python = ">=3.10"
license = {text = "MIT"}

[tool.pdm]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
