[build-system]
build-backend = "pdm.pep517.api"
requires = ["pdm-pep517>=1.0.0"]

[project]
authors = [
  {name = "Harsh Dadhich", email = "hdadhich01@gmail.com"}
]
dependencies = ["beautifulsoup4", "cchardet", "deta", "flask", "flask-compress", "flask-cors", "flask-limiter", "gunicorn", "httpx", "humanize", "lxml", "orjson", "python-dotenv", "round-nutrition", "schedule", "sentry-sdk[flask]", "thefuzz[speedup]"]
description = "🔧 Simple REST API to return compiled data on university services"
license = {text = "MIT"}
name = "SlugTools API"
requires-python = ">=3.10"

[tool.pdm]
