[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Harsh Dadhich", email = "hdadhich01@gmail.com"},
]
dependencies = ["beautifulsoup4", "cchardet", "deta[async]==1.1.0a2", "python-dotenv", "flask[async]", "flask-cors", "flask-limiter", "gunicorn", "lxml", "orjson", "python-levenshtein", "requests", "round-nutrition", "thefuzz"]
requires-python = ">=3.10"
license = {text = "MIT"}

[tool.pdm]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
