name: Deploy to DigitalOcean

on:
  push:
    branches:
      - live

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DigitalOcean

    steps:
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: api
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
